`timescale 1ns / 1ps

// NVM Controller Control FSM
//
// Responsibilities:
// 1. Select READ, PROGRAM, or ERASE operation.
// 2. Control the Flash interface.
// 3. Generate WD_CAPTURE_EN for the Write Data Register.
// 4. Generate read_active for the Flash Interface.
// 5. Generate HREADYOUT and HRESP for the AHB-Lite interface.
// 6. Wait for Flash completion or error.
//
// Program sequence:
// IDLE -> PROGRAM_DATA -> PROGRAM_START -> PROGRAM_WAIT
//
// Flash interface assumptions:
// - FLASH_PROG_EN starts programming after address and data are valid.
// - FLASH_RD_EN is a one-cycle read-start command.
// - FLASH_ERASE_EN is a one-cycle erase-start command.
// - FLASH_DONE indicates successful operation completion.
// - FLASH_ERROR indicates operation failure.
// - read_active remains high throughout an active read operation.

module nvm_control_fsm (

    // Clock and reset
    input  wire        clk,
    input  wire        reset_n,

    // AHB transaction information
    input  wire        valid_transfer,
    input  wire        addr_valid,
    input  wire        flash_region,
    input  wire        erase_region_select,
    input  wire        hwrite_reg,

    // Flash status
    input  wire        flash_busy,
    input  wire        flash_done,
    input  wire        flash_error,

    // Flash control outputs
    output reg         flash_cs,
    output reg         flash_rd_en,
    output reg         flash_prog_en,
    output reg         flash_erase_en,

    // Read operation status
    output reg         read_active,

    // Write-data capture control
    output reg         wd_capture_en,

    // AHB response outputs
    output reg         hreadyout,
    output reg         hresp
);


    //============================================================
    // State Encoding
    //============================================================

    localparam [3:0] IDLE          = 4'd0;
    localparam [3:0] READ_START    = 4'd1;
    localparam [3:0] READ_WAIT     = 4'd2;
    localparam [3:0] PROGRAM_DATA  = 4'd3;
    localparam [3:0] PROGRAM_START = 4'd4;
    localparam [3:0] PROGRAM_WAIT  = 4'd5;
    localparam [3:0] ERASE_START   = 4'd6;
    localparam [3:0] ERASE_WAIT    = 4'd7;
    localparam [3:0] ERROR_STATE   = 4'd8;


    //============================================================
    // AHB Response Encoding
    //============================================================

    localparam HRESP_OKAY  = 1'b0;
    localparam HRESP_ERROR = 1'b1;


    //============================================================
    // State Registers
    //============================================================

    reg [3:0] current_state;
    reg [3:0] next_state;


    //============================================================
    // Sequential State Register
    //============================================================

    always @(posedge clk or negedge reset_n) begin

        if (!reset_n) begin
            current_state <= IDLE;
        end
        else begin
            current_state <= next_state;
        end

    end


    //============================================================
    // Next-State Logic
    //============================================================

    always @(*) begin

        // Default: remain in current state
        next_state = current_state;

        case (current_state)

            //====================================================
            // IDLE
            //====================================================

            IDLE: begin

                if (valid_transfer) begin

                    // Invalid address
                    if (!addr_valid) begin
                        next_state = ERROR_STATE;
                    end

                    // Flash/NVM region
                    else if (flash_region) begin

                        // HWRITE = 0 -> READ
                        if (!hwrite_reg) begin
                            next_state = READ_START;
                        end

                        // HWRITE = 1 -> PROGRAM
                        else begin
                            next_state = PROGRAM_DATA;
                        end

                    end

                    // Erase region
                    else if (erase_region_select) begin

                        // Erase is a write operation
                        if (hwrite_reg) begin
                            next_state = ERASE_START;
                        end

                        // Read from erase region is invalid
                        else begin
                            next_state = ERROR_STATE;
                        end

                    end

                    // Should not normally occur if addr_valid
                    // is correctly generated by the address decoder
                    else begin
                        next_state = ERROR_STATE;
                    end

                end

            end


            //====================================================
            // READ_START
            //====================================================

            READ_START: begin

                // Issue one-cycle Flash read command
                next_state = READ_WAIT;

            end


            //====================================================
            // READ_WAIT
            //====================================================

            READ_WAIT: begin

                if (flash_error) begin
                    next_state = ERROR_STATE;
                end

                else if (flash_done) begin
                    next_state = IDLE;
                end

            end


            //====================================================
            // PROGRAM_DATA
            //====================================================

            PROGRAM_DATA: begin

                // HWDATA is captured by the Write Data Register
                // while this state is active.

                next_state = PROGRAM_START;

            end


            //====================================================
            // PROGRAM_START
            //====================================================

            PROGRAM_START: begin

                // Address and write data are already available.
                // Start Flash programming.
                next_state = PROGRAM_WAIT;

            end


            //====================================================
            // PROGRAM_WAIT
            //====================================================

            PROGRAM_WAIT: begin

                if (flash_error) begin
                    next_state = ERROR_STATE;
                end

                else if (flash_done) begin
                    next_state = IDLE;
                end

            end


            //====================================================
            // ERASE_START
            //====================================================

            ERASE_START: begin

                // Issue one-cycle Flash erase command
                next_state = ERASE_WAIT;

            end


            //====================================================
            // ERASE_WAIT
            //====================================================

            ERASE_WAIT: begin

                if (flash_error) begin
                    next_state = ERROR_STATE;
                end

                else if (flash_done) begin
                    next_state = IDLE;
                end

            end


            //====================================================
            // ERROR_STATE
            //====================================================

            ERROR_STATE: begin

                // Detailed AHB error handling will be finalized
                // in the Status/Error Logic.
                next_state = IDLE;

            end


            //====================================================
            // Default
            //====================================================

            default: begin
                next_state = IDLE;
            end

        endcase

    end


    //============================================================
    // Moore Output Logic
    //============================================================
    //
    // All outputs depend only on current_state.
    //
    //============================================================

    always @(*) begin

        //========================================================
        // Default values
        //========================================================

        flash_cs       = 1'b0;

        flash_rd_en    = 1'b0;
        flash_prog_en  = 1'b0;
        flash_erase_en = 1'b0;

        read_active    = 1'b0;
        wd_capture_en  = 1'b0;

        hreadyout      = 1'b1;
        hresp          = HRESP_OKAY;


        //========================================================
        // State-dependent outputs
        //========================================================

        case (current_state)

            //====================================================
            // IDLE
            //====================================================

            IDLE: begin

                flash_cs       = 1'b0;

                flash_rd_en    = 1'b0;
                flash_prog_en  = 1'b0;
                flash_erase_en = 1'b0;

                read_active    = 1'b0;
                wd_capture_en  = 1'b0;

                hreadyout      = 1'b1;
                hresp          = HRESP_OKAY;

            end


            //====================================================
            // READ_START
            //====================================================

            READ_START: begin

                flash_cs       = 1'b1;
                flash_rd_en    = 1'b1;

                // Read operation is active.
                read_active    = 1'b1;

                hreadyout      = 1'b0;
                hresp          = HRESP_OKAY;

            end


            //====================================================
            // READ_WAIT
            //====================================================

            READ_WAIT: begin

                flash_cs       = 1'b1;

                // Keep read operation identified as active
                // until Flash reports completion or error.
                read_active    = 1'b1;

                hreadyout      = 1'b0;
                hresp          = HRESP_OKAY;

            end


            //====================================================
            // PROGRAM_DATA
            //====================================================

            PROGRAM_DATA: begin

                // Capture HWDATA into Write Data Register.
                wd_capture_en  = 1'b1;

                hreadyout      = 1'b0;
                hresp          = HRESP_OKAY;

            end


            //====================================================
            // PROGRAM_START
            //====================================================

            PROGRAM_START: begin

                // Address and write data are now available.
                flash_cs       = 1'b1;
                flash_prog_en  = 1'b1;

                hreadyout      = 1'b0;
                hresp          = HRESP_OKAY;

            end


            //====================================================
            // PROGRAM_WAIT
            //====================================================

            PROGRAM_WAIT: begin

                flash_cs       = 1'b1;

                hreadyout      = 1'b0;
                hresp          = HRESP_OKAY;

            end


            //====================================================
            // ERASE_START
            //====================================================

            ERASE_START: begin

                flash_cs       = 1'b1;
                flash_erase_en = 1'b1;

                hreadyout      = 1'b0;
                hresp          = HRESP_OKAY;

            end


            //====================================================
            // ERASE_WAIT
            //====================================================

            ERASE_WAIT: begin

                flash_cs       = 1'b1;

                hreadyout      = 1'b0;
                hresp          = HRESP_OKAY;

            end


            //====================================================
            // ERROR_STATE
            //====================================================

            ERROR_STATE: begin

                flash_cs       = 1'b0;

                flash_rd_en    = 1'b0;
                flash_prog_en  = 1'b0;
                flash_erase_en = 1'b0;

                read_active    = 1'b0;
                wd_capture_en  = 1'b0;

                // Temporary behavior.
                // Detailed error response will be handled
                // by Status/Error Logic.
                hreadyout      = 1'b1;
                hresp          = HRESP_ERROR;

            end


            //====================================================
            // Default
            //====================================================

            default: begin

                flash_cs       = 1'b0;

                flash_rd_en    = 1'b0;
                flash_prog_en  = 1'b0;
                flash_erase_en = 1'b0;

                read_active    = 1'b0;
                wd_capture_en  = 1'b0;

                hreadyout      = 1'b1;
                hresp          = HRESP_OKAY;

            end

        endcase

    end

endmodule